tap "hashicorp/tap"

# Homebrew packages
brew "awscli"
brew "bash"
brew "bazelisk"
brew "blackbox"
brew "ctlptl"
brew "curl"
brew "docker-compose"
brew "doctl"
brew "fzf"
brew "gh"
brew "gnupg"
brew "goenv"
brew "grip"
brew "hadolint"
brew "hashicorp/tap/terraform-ls"
brew "helm"
brew "htop"
brew "huggingface-cli"
brew "imagemagick"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "mas"
brew "neovim"
brew "nvm"
brew "pcre"
brew "pinentry-mac"
brew "pyenv"
brew "rbenv"
brew "ripgrep"
brew "shellcheck"
brew "tfenv"
brew "tflint"
brew "tilt"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "watch"
brew "wget"
brew "ykman"
brew "yq"

# Mac App Store Apps
mas "Amphetamine", id: 937984704
mas "Slack for Desktop", id: 803453959
mas "Yubico Authenticator", id: 1497506650
