services:
  dorker:
    image: darthfork/dorker:latest
    hostname: dorker
    stdin_open: true
    tty: true
    environment:
      - AWS_PROFILE
    volumes:
      - $HOME/workspace:/darthfork/workspace
      - $HOME/.aws:/darthfork/.aws
      - $HOME/.kube:/darthfork/.kube
      - $HOME/.helm:/darthfork/.helm
    ports:
      - 20022:20022
    entrypoint: /usr/bin/env bash
