services:
  dorker:
    image: darthfork/dorker:latest
    hostname: dorker
    stdin_open: true
    tty: true
    environment:
      - AWS_PROFILE
      - DO_TOKEN
    volumes:
      - $HOME/workspace:/darthfork/workspace
      - $HOME/.aws:/darthfork/.aws
      - $HOME/.kube:/darthfork/.kube
    entrypoint: /bin/bash
