version: "3"
services:
  dorker:
    image: darthfork/dorker:latest
    hostname: dorker
    stdin_open: true
    tty: true
    environment:
      - AWS_PROFILE
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $HOME/workspace:/workspace
      - $HOME/.aws:/root/.aws
      - $HOME/.kube:/root/.kube
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash
