version: "3"
services:
  dorker:
    image: darthfork/dorker:latest
    hostname: dorker
    stdin_open: true
    tty: true
    environment:
      - AWS_PROFILE
    volumes:
      - /Users/abhishekrai/.ssh:/root/.ssh
      - /Users/abhishekrai/workspace:/workspace
      - /Users/abhishekrai/.aws:/root/.aws
      - /Users/abhishekrai/.kube:/root/.kube
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash
